services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "testdb"
    expose:
      - 3306
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  backend:
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_DB: "testdb"
      CORS: "http://localhost:8080"
    build: ../../GHPF-Backend/.
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: 
      context: ../../GHPF-Frontend/.
      args:
        - REACT_APP_APIURL=http://localhost:3000
    ports:
      - "8080:80"