{
 "title": "API Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_total{status_code=\"200\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    { "expression": "$A/1000000", "type": "math" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"backend-api-598df489cd-6ht25\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"backend-api\"} |= `info`"
    }
   ]
  },
  {
   "title": "Error  Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{container=\"backend-api\"} |= `error`"
    }
   ]
  }
 ]
}