apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argo-cd
spec:
  destination:
    namespace: geekhub
    server: 'https://kubernetes.default.svc'
  source:
    path: backend
    repoURL: 'https://github.com/AlejoHarris/GHPF-K8S.git'
    targetRevision: HEAD
  project: geekhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
