apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  destination:
    namespace: geekhub
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/AlejoHarris/GHPF-K8S.git'
    targetRevision: HEAD
  project: geekhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
