apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argo-cd
spec:
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: promtail
    repoURL: 'https://github.com/AlejoHarris/GHPF-K8S.git'
    targetRevision: HEAD
  project: geekhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
